---
- name: Copy scap rpm to host
  copy:
     src: scc-5.0.2.rhel7.x86_64.rpm
     dest: /tmp/scc-5.0.2.rhel7.x86_64.rpm

- name: Install scap package
  yum:
    name: /tmp/scc-5.0.2.rhel7.x86_64.rpm
    state: present 

- name: copy rhel xml file
  copy: 
     src: U_Red_Hat_Enterprise_Linux_7_V2R3_STIG_SCAP_1-2_Benchmark.xml
     dest: /tmp/U_Red_Hat_Enterprise_Linux_7_V2R3_STIG_SCAP_1-2_Benchmark.xml

- name: Enable rhel scap content
  args: 
     chdir: /opt/scc
  command: "./cscc {{ item }}"
  with_items:
    - -is --force /tmp/U_Red_Hat_Enterprise_Linux_7_V2R3_STIG_SCAP_1-2_Benchmark.xml
    - --setProfile  MAC-2_Classified RHEL_7_STIG 
